### ISSUE TITLE
S-102 Initial catalogue

### ISSUE THREAD

**Issue by mikan66** [iho-ohi/S-102-Portrayal-Catalogue#1]
Create baseline portrayal catalogue for S-102 version 3.0.0 built to S-100 5.2 schemas.

**Comment by mikan66** [comment]
Initial baseline checked in.  Can be used to experiment with data produced to FC 2.1 as checked in here.  See commit https://github.com/iho-ohi/S-102-Portrayal-Catalogue/commit/a6c5fe2121157b1b975611cb06995c997a707408

**Comment by VasGenTester** [comment]
> Initial baseline checked in. Can be used to experiment with data produced to FC 2.1 as checked in here. See commit [a6c5fe2](https://github.com/iho-ohi/S-102-Portrayal-Catalogue/commit/a6c5fe2121157b1b975611cb06995c997a707408)

Dear @mikan66 


I have a question about backward compatibility of different version of S-102 charts/FC/PC. 

The latest **official** edition of IHO S-102 standard (ed.3.0.0 - https://registry.iho.int/testbed/view.do?idx=215&product_ID=S-102&statusS=ALL&domainS=ALL&category=product_ID&searchValue=) contains the following phrase:
**1.6.3. Revision**
...
Changes in a revision are minor and **ensure backward compatibility with the previous versions within the same Edition**. Newer revisions, for example, introduce new features and attributes. Within the same Edition, a dataset of one version could always be processed with a later version of the Feature and Portrayal Catalogues.

That is because you pointed that FC v.3.0.0 can be used with S-102 chart v.2.x


But what is the common approach with "Revision" number across different S-1xx standards?

E.g. if look inside the latest **draft** edition of S-98 (which is 1.5.3 dated September 2024 - https://github.com/iho-ohi/98-interoperability/tree/main/documents/F2F-Documents) we can see that the above text was removed:
C-24.1	Multiple product versions and portrayal
![image](https://github.com/user-attachments/assets/ea03fd3b-659a-4d32-8735-a3562b83c4c1)


Looks like there will be a strict rule (at least for S-101 data) that system (ECDIS or whatever) should not display S-101 chart if used FC or PC has a different "Edition" or "Revision" number.
E.g. you will not be able to display S-101 chart v.1.4.0 with FC v.1.5.0 or PC v.1.5.0

Would S-102 data in future be processed in the same way as S-101?

**Comment by mikan66** [comment]
The fact that S-102 v3.0.0 could work with v2.X datasets is just to support developmental efforts as an OEM and generally should not be expected to work.  When components don't match, expect to make software code changes as hacks to force things to work.  When all components are aligned with matching versions any software changes required should be considered as forward enhancements to the system.
