### ISSUE TITLE
Description of `SafetyContour` differs between Lua and XSLT

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-102-Portrayal-Catalogue#15]
`Selected` vs. `selected`: Use `Selected`.

**Comment by RohdeBSH** [comment]
Hi @DavidGrant-NIWC,

The label is not correct. This change is required for S-102 ed. 3.0.0 as requested in the German comments sheet for edition 3.0.0.

**Comment by DavidGrant-NIWC** [comment]
3.0.0 has already been released. Unless there is a desire to release version 3.0.1 new issues should target 3.1.0.

In any case, it seems this issue is OBE; the XSLT PC will be removed in the 3.1.0 release. Will review the minutes from PT19 when available prior to closing this issue.

**Comment by RohdeBSH** [comment]
It must be changed in release 3.0.0, in my opinion.
There was a stakeholder review of the S-100WG for the S-102 ed 3.0.0. This resulted in the comments, which must now be incorporated. Since S-102PT19 has approved the changes. The changes will then replace the previous S-102 ed 3.0.0. The standard will only be published/released after Member State approval.

Otherwise we wouldn't have the stress of revising everything by 08.09.2024. Then Lawrence could have done everything in peace and quiet when he returns in October.

**Comment by AnnaWall01** [comment]
My understanding is the same as Daniel's. The points in the comment sheet are the things that we need to change during the review/endorsement period, that will then go back to S-100WG. This needs to be done by the 8th of September.

@https://github.com/CHS-LynnPatterson Can you confirm that this is the decision from PT19?

**Comment by mikan66** [comment]
If we make changes to PC 3.0.0 the version should be updated at least in the most minor digit, i.e. 3.0.1, otherwise there will be two releases of the PC with the same version.  This is the purpose of the 3rd digit while maintaining compatibility with FC 3.0.0.  Ultimately, it's this WG's decision.  Let me know and then we'll remove the XSLT and whatever is required.

**Comment by RohdeBSH** [comment]
This is only an issue to the GitHub release, because there is no release of S-102 ed. 3.0.0. And GitHub doesn't matter.

**Comment by RohdeBSH** [comment]
I have to change all driver names currently implement from 3.0.0 to 3.0.1 and the other OEMs also. Just because of the difference of small and large "s" in a standard  that has not been published.

**Comment by mikan66** [comment]
OBE with commits eba82e85995db10cbf6e470ce46c3861cef83215, 1cfd0748b7df11a3860afd9333baed3aed446124
