### ISSUE TITLE
FC attributes don't match BSH sample data

### ISSUE THREAD

**Issue by mikan66** [iho-ohi/S-102-Portrayal-Catalogue#7]
@hasel001, The FC defined in main at https://github.com/iho-ohi/S-102-Portrayal-Catalogue/issues/2#issuecomment-2146084337 
does not match v3.0 sample data from BSH. The Group_F definitions disagree with the FC definitions.  This needs harmonization as to which is correct (FC or sample HDF5 v3.0 sample dataset).

In the sample dataset BathymetryCoverage has single attribute defined: "depth".
![image](https://github.com/user-attachments/assets/ea5d9bd8-eea0-4107-93ab-3c782a661151)

In the sample dataset QaulityOfBathymetryCoverage has single attribute defined: "iD"
![image](https://github.com/user-attachments/assets/e2c2cada-2331-42be-9890-1d26ccfa8e51)

**Comment by hasel001** [comment]
So, BSH are fervent proponents of data standing on its own without uncertainty, which is likely why their sample data

**Comment by RohdeBSH** [comment]
Hi @hasel001 & @mikan66,

The BSH test data sets use the latest FC. The FC linked in issue #2 is no longer up to date. Perhaps I should have included it in the ExchangeSet. Unfortunately, I didn't think of that.
It still comes from the adaptation branch. In the meantime, however, we are back in the developing branch and that is where the current FCs are located. This is exactly the reason why I didn't think it was a good idea to separate the repositories.

Since edition 2.2.0, uncertainty is optional if it is uniform across the entire data set. Since the BSH does not provide any information about the uncertainty, it is uniform for us (fillValue). We have therefore removed the uncertainty from Group_F in accordance with the specification. Compliant with the FC (uncertainty 0...1).

The problem with the "iD"...
The attribute "iD" has now been registered in the IHO GI registry.  Unfortunately not in lower case, but in CamelCase form. The FC has also been corrected accordingly, as have DCEG and the text document. The problem now is that the name of the attribute "iD" (CamelCase) in the QOBC-values is not identical to the name of the "id" (lowerCase) column in the FeatureAttributeTable.

The BSH data set is correct. The only correction needed from @mikan66 screenshot is, that I forgot to insert the "Name"-column.
The latest FC is [here](https://github.com/iho-ohi/S-102-Product-Specification/blob/Developing/sources/3.0.0/FC/S-102_Ed_3.0.0_FC.xml).
What had been registered for "iD" is [here](https://github.com/iho-ohi/S-102-Product-Specification/commit/01f690bd636354fae9bf95c4eb3b5cca93755789#r144378204).
The optional uncertainty can be found in chapter 9.2.7.

> If the uncertainty for each grid cell is equal, it is not necessary to store it at each cell in the grid. The uniqueness of the uncertainty results from the equality of the attributes minimumUncertainty and maximumUncertainty of Group_001 of the BathymetryCoverage (see [Table 10](file:///C:/Users/bn2110/Downloads/github-pages/documents/3.0.0/document.html#tab-attributes-of-values-group) No. 3 & 4). If the uncertainty values at the grid cells are omitted, it must be ensured that the entry of the uncertainty of the BathymetryCoverage in the Group_F is also omitted (see Table 6). This type of storage technique can reduce the amount of memory required for the uncertainty without loss of information. The uncertainty of each grid cell can be immediately obtained from the minimumUncertainty or maximumUncertainty attributes of Group_001 of the BathymetryCoverage.

**Comment by mikan66** [comment]
It's OK if the repos are separate, I just need to know where the official FC copy resides when updates are needed. We'll put a "courtesy copy" of the official FC with the PC here.  That's what we do for S-101, which is much more dynamic.  

Generally speaking, the FC and HDF5 structure for features and attributes must match EXACTLY.  I'll need sample data that matches the official FC and I'll revisit with more testing of everything.  Optional S-102 attributes with HDF5 encoding might be a new twist that we'll need to address in our S-100 HDF5 driver.

**Comment by mikan66** [comment]
Everything tested as v3.0.0 (FC/PC/Dataset) with some quick changes to our S100Viewer Testbed.  I'll have @DavidGrant-NIWC review then we can advance this for submittal to S-100 WG by the end of the week.
![image](https://github.com/user-attachments/assets/1fc45974-5df8-4fdb-9a13-fc87fc832cb1)

**Comment by VasGenTester** [comment]
Dear @mikan66 

Are there any open repositories (or links) from where I can download S-102 data ed.3.0.0?

**Comment by mikan66** [comment]
> Dear @mikan66
> 
> Are there any open repositories (or links) from where I can download S-102 data ed.3.0.0? I see that you mentioned some BSH data.

Sorry, I am not aware of any public data supporting version 3.  Maybe the WG Chair can arrange for a few samples?

**Comment by RohdeBSH** [comment]
Dear @VasGenTester ,

The BSH is always willing to support the development of IHO standards in the interests of maritime safety.
In the case of S-102 data, this data is subject to some regulations on national safety aspects of the Federal Republic of Germany. It is therefore not possible to provide test data across the board. 
If you are interested in test data, you are welcome to contact customer[at]bsh.de with your request.
Please explain your request, the purpose and your background (e.g. company, organization).
Please understand that test data cannot be provided to private individuals.

**Comment by VasGenTester** [comment]
> Dear @VasGenTester ,
> 
> The BSH is always willing to support the development of IHO standards in the interests of maritime safety. In the case of S-102 data, this data is subject to some regulations on national safety aspects of the Federal Republic of Germany. It is therefore not possible to provide test data across the board. If you are interested in test data, you are welcome to contact customer[at]bsh.de with your request. Please explain your request, the purpose and your background (e.g. company, organization). Please understand that test data cannot be provided to private individuals.


Dear @RohdeBSH 

I'm not an individual. I work as SW test engineer in Navtor AS and our SW supports different S-1xx data.
I know where to get both real and test data for S-102 ed.2.x but want to test our SW against ed.3.0.0 also.
That is because I was asking.

But thank you for you answer - will ask BSH customer support.

**Comment by VasGenTester** [comment]
> > Dear @mikan66
> > Are there any open repositories (or links) from where I can download S-102 data ed.3.0.0? I see that you mentioned some BSH data.
> 
> Sorry, I am not aware of any public data supporting version 3. Maybe the WG Chair can arrange for a few samples?


Dear @mikan66 

Thank you for your answer.
Then the last question - do you have a contacts (link) of this person? I mean to whom exactly I should write?

**Comment by mikan66** [comment]
> > > Dear @mikan66
> > > Are there any open repositories (or links) from where I can download S-102 data ed.3.0.0? I see that you mentioned some BSH data.
> > 
> > 
> > Sorry, I am not aware of any public data supporting version 3. Maybe the WG Chair can arrange for a few samples?
> 
> Dear @mikan66
> 
> Thank you for your answer. Then the last question - do you have a contacts (link) of this person? I mean to whom exactly I should write?

The IHO may have broader insight into additional datasets.  Reach out directly via IHO website at: https://iho.int/en/contact  and email with your inquiry to: info@iho.int.  It's possible the S-102 WG Chair is not available and someone else is filling in.  Generally, the most "up-to-date" S-102 datasets against the latest spec revision has been in short supply.  Ed 3.0.0 is relatively "new".

**Comment by DavidGrant-NIWC** [comment]
For others who may come across this discussion, my understanding is that test data will ultimately be made available via S-164. The S-164 development repo is here: https://github.com/iho-ohi/S-164-Sub-Group

Currently S-164 only contains S-101 data; recommend adding a watch for awareness of changes to the available test data.
